### ISSUE TITLE
Populating inherited properties

### ISSUE THREAD

**Issue by engtecmat** [zhezhangz/easy-modeling#3]
### Describe the feature

Hi @zhezhangz, thanks for this library. 

I'm writing for asking if there's a feature that can populate the properties that inherit from the superclass?

### Use Case

```
public class Animal {
    private String name;
}
```

```
public class Person extends Animal {
  private String healthCode;
}
```

```
@Test
void test_subtype() throws JsonProcessingException {
  final Person person = PersonModeler.builder().build();

  assertThat(person.getHealthCode()).isNotNull();
  assertThat(person.getName()).isNotNull();
}
```
```
Expecting actual not to be null
java.lang.AssertionError: 
Expecting actual not to be null
```

### Acknowledgements

- [ ] I may be able to implement this feature
- [ ] This feature will introduce some breaking changes

### EasyModeling Version

0.1.0-release

**Comment by zhezhangz** [comment]
@engtecmat Thanks for the great catch! That should be an important feature missing in the design. 
I have to implement it asap.
